Increase visibility of internal timeouts
Because test timeouts normally timeout before timeouts on
things like `waitForEvent` error messages lose useful information.

Therefore reduce the default timeout on indivdual events.

This changes an error from something like:

```
Error: Timeout of 5000ms exceeded. For async
tests and hooks, ensure "done()" is called;
if returning a Promise, ensure it resolves.
```

to something like:

```
Error: no event 'terminated' received after 4000 ms
```